# All possible commands: https://nikitabobko.github.io/AeroSpace/commands
after-login-command = []

after-startup-command = []

start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = 'tiles'

default-root-container-orientation = 'horizontal'

key-mapping.preset = 'qwerty'

# on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See: https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 5
inner.vertical =   5
# outer.top = [{ monitor.'LG ULTRAWIDE' = 45 }, 5]
# outer.top = [{ monitor.'LG ULTRAWIDE' = 5 }, { monitor.'Built-in Retina Display' = 10 }, 5]
outer.top =        5
outer.right =      5
outer.bottom =     5
outer.left =       5

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
t = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift

# See: https://nikitabobko.github.io/AeroSpace/commands#exec-and-forget
# You can uncomment the following lines to open up terminal with alt + enter shortcut (like in i3)
# alt-enter = '''exec-and-forget osascript -e '
# tell application "Terminal"
#     do script
#     activate
# end tell'
# '''

alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# === Windows ===
cmd-alt-t = 'layout floating tiling'

cmd-alt-h = 'focus left'
cmd-alt-j = 'focus down'
cmd-alt-k = 'focus up'
cmd-alt-l = 'focus right'

cmd-alt-shift-h = 'move left'
cmd-alt-shift-j = 'move down'
cmd-alt-shift-k = 'move up'
cmd-alt-shift-l = 'move right'

cmd-alt-enter = 'fullscreen'

cmd-alt-shift-minus = 'resize smart -50'
cmd-alt-shift-equal = 'resize smart +50'

cmd-ctrl-alt-shift-h = ['join-with left', 'mode main']
cmd-ctrl-alt-shift-j = ['join-with down', 'mode main']
cmd-ctrl-alt-shift-k = ['join-with up', 'mode main']
cmd-ctrl-alt-shift-l = ['join-with right', 'mode main']

# === Workspaces ===
cmd-ctrl-1 = 'workspace 1'
cmd-ctrl-2 = 'workspace 2'
cmd-ctrl-3 = 'workspace 3'
cmd-ctrl-4 = 'workspace 4'

cmd-ctrl-shift-1 = 'move-node-to-workspace 1'
cmd-ctrl-shift-2 = 'move-node-to-workspace 2'
cmd-ctrl-shift-3 = 'move-node-to-workspace 3'
cmd-ctrl-shift-4 = 'move-node-to-workspace 4'

# === Monitors ===
cmd-ctrl-h = 'focus-monitor left'
cmd-ctrl-l = 'focus-monitor right'

cmd-ctrl-shift-h = 'move-node-to-monitor left'
cmd-ctrl-shift-l = 'move-node-to-monitor right'

alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# === Applications ===

# Kitty
cmd-ctrl-alt-t = 'exec-and-forget open -n /Applications/kitty.app/Contents/MacOS/kitty --single-instance -d ~'
# Brave
cmd-ctrl-alt-b = 'exec-and-forget open -n /Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser'
# Arc
cmd-ctrl-alt-a = 'exec-and-forget open -n /Applications/Arc.app/Contents/MacOS/Arc'
# Obsidian
cmd-ctrl-alt-o = 'exec-and-forget open -n /Applications/Obsidian.app/Contents/MacOS/Obsidian & exit'

# === Modes ===
alt-shift-semicolon = 'mode service'

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

# === Move Apps ===

# Show IDs: aerospace list-apps
[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'net.kovidgoyal.kitty'
run = 'move-node-to-workspace 2'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 2'


